# Generated by Django 5.1.1 on 2024-09-11 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_tasks_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ('-time_created',), 'verbose_name': 'Задачи на ближайшее время'},
        ),
        migrations.AlterField(
            model_name='tasks',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('Not started', 'Не начато'), ('In progress', 'В процессе'), ('Completed', 'Выполнено')], default='Not started', max_length=30),
        ),
        migrations.AddIndex(
            model_name='tasks',
            index=models.Index(fields=['-time_created'], name='tasks_tasks_time_cr_80a8f4_idx'),
        ),
    ]
