# Generated by Django 5.1.1 on 2024-09-15 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_tasks_options_alter_tasks_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ('-time_created',), 'verbose_name': 'Задачи'},
        ),
    ]
