# Generated by Django 5.1.1 on 2024-09-16 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_tasks_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ('-time_created',), 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
